### ISSUE TITLE
No title, url or motion text to submit the proposal.

### ISSUE THREAD

**Issue by baolongt** [peterpeterparker/proposals.network#49]
![image](https://github.com/user-attachments/assets/420bcd77-9d4d-483c-88d9-505b0a17bf40)
I got this even I put all the the form

**Comment by baolongt** [comment]
https://proposals.network/submit?g=rrkah-fqaaa-aaaaa-aaaaq-cai&key=uRtwpKpeTDWwfi-1P1WHr

**Comment by peterpeterparker** [comment]
Data are correctly saved in the backend.

You are trying to submit a proposal to ICP NNS (`rrkah-fqaaa-aaaaa-aaaaq-cai`), not a SNS, that's correct? 

What device and browser are you using?

Have you try to go back to home screen, reload and retry?

**Comment by baolongt** [comment]
wait is that a way to make proposal to gold DAO?

**Comment by peterpeterparker** [comment]
You have first to select Gold DAO on the main screen.

Then make a proposal.

UX can be improved agree. PR welcome btw.

I have to go offline for a bit, if you provide more details and still does not work, I can answer later and/or debug tomorrow.

<img width="1536" alt="Capture d’écran 2024-07-17 à 19 04 51" src="https://github.com/user-attachments/assets/59aa151f-0100-4345-888a-0d73cda644a5">

<img width="1536" alt="Capture d’écran 2024-07-17 à 19 05 10" src="https://github.com/user-attachments/assets/762dda57-a28b-4c50-a072-d746b5930fcf">

**Comment by baolongt** [comment]
Ok it kinda confuse but I think I got it. Maybe because the neuron is from GOLD DAO instead of ICP. It can be a bug

**Comment by peterpeterparker** [comment]
I cannot reproduce the issue 🤷‍♂️

Did it ultimately worked out for you?

**Comment by baolongt** [comment]
No still not, the GOLD DAO needed to upgrade the version to create proposal. It failed

![image](https://github.com/user-attachments/assets/092e890c-0f1a-4bca-a75c-de8fbf93c400)

**Comment by peterpeterparker** [comment]
Not sure what's happening. You have some stagged unrelated data - i.e. the errors displayed in the console are unrelated, like you have other draft in memory.

If you try in another browser or if you sign-out/sign-in it might resolve the issue. Can you try?

Not the solution to the bug but, just to unblock you.

**Comment by peterpeterparker** [comment]
I've been debugging for last hour and was not able to reproduce the issue.
However, reading this thread again, it feels like the error message is correct.

According your screenshot you indeed did not provided an URL pointing to the forum!

<img width="823" alt="Capture d’écran 2024-07-18 à 17 59 25" src="https://github.com/user-attachments/assets/9b57963d-25fd-4e4c-bb29-78873ce9391c">

Can you provide one and try to submit your proposal again?

**Comment by baolongt** [comment]
![image](https://github.com/user-attachments/assets/f023e1ac-8448-42f2-9bca-ff00d0dff1fa)
It kinda confuse if you don't put required in there, but look at this error

![image](https://github.com/user-attachments/assets/479cbadc-9a64-4aac-b2e4-b245abafb3c2)
![image](https://github.com/user-attachments/assets/b1d40043-a706-43d2-b99a-f9b093e6d072)

**Comment by peterpeterparker** [comment]
> It kinda confuse if you don't put required in there

All fields are required, so you can assume that all information is necessary. Additionally, I prefer a positive approach to buttons rather than disabling actions.

> Submit error

The error does not come from proposals.network but, from the governance of Gold DAO. Unless there is an issue with the display of the requirement - i.e. is 100 GLDGov correct? - not sure what's the issue. You have set the hotkey correct?

**Comment by peterpeterparker** [comment]
Unrelated, I've now added a "Governance picker" which is displayed on "Submit a proposal"

<img width="1536" alt="Capture d’écran 2024-07-21 à 14 57 00" src="https://github.com/user-attachments/assets/3de5ad2d-5a86-459b-8536-bd74a79636b3">

**Comment by peterpeterparker** [comment]
It took me a long time to replicate Gold DAO locally. My dfx replica crashed twice, and I had to submit several proposals to spin up a similar SNS. Ultimately, I finally managed to generate the project and was able to replicate your issue.

It seems that while I'm displaying 100 GLDGov as the minimal neuron stake to submit an SNS motion proposal, the Governance canister is actually expecting 1,000 GLDGov. For example, locally I wasn't able to submit a proposal with 999 GLDGov, but I was able to successfully submit one with 1,000 GLDGov.

As I don't understand why there is this discrepancy and really cannot pinpoint the cause, I have opened a thread on the [forum](https://forum.dfinity.org/t/gold-dao-minimal-neuron-stake-to-submit-proposal/33476).

**Comment by peterpeterparker** [comment]
I found it. I used the wrong field in the UI. Dumb me, I was using minimal neuron stake to display the minimal stake but, actually it the stake that should cover at least the minimal rejection fee. In case of Gold DAO, the rejection fee is 1,000 and no 100.

**Comment by peterpeterparker** [comment]
I have implemented a UI fix #52 and it has been rolled out.

So, long story short, you need at least a neuron with 1,000 GLDGov staked to submit a motion proposal to Gold DAO.

**Comment by baolongt** [comment]
I'm too broke to have 1000 GLDGov so I closed this as resolved issue
